# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: halcyon_dongle//zmk
    shield: lambbt_dongle
    artifact-name: lambbt_central
    
  - board: nice_nano@2.0.0//zmk
    shield: lambbt_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lambbt_left
  - board: nice_nano@2.0.0//zmk
    shield: lambbt_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lambbt_right

  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
    artifact-name: splits_settings_reset
  - board: halcyon_dongle//zmk
    shield: settings_reset
    artifact-name: dongle_settings_reset
